const { Schema, default: mongoose } = require("mongoose");

const disputeSchema=new Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    addOnId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'addon-services',
        required:true
    },
    addOnType:{
        type:String,
        required:true
    },
    addOnPrice:{
        type:Number,
        required:true
    },
    against:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    type:{
        type:String,
        required:true
    },
    subject:{
        type:String,
        required:true
    },
    message:{
        type:String
    },
    image:{
        type:String
    },
    email:{
        type:String
    },    
    country:{
        type:String
    },
    zipCode:{
        type:String,
    },
    phoneNumber:{
        type:String
    },
    cardInformation:{
        cardHolderName:String,
        cardNumber:String,
        expiryDate:String,
        cvv:String
    },
    serviceUsed:{type:Boolean,default:false},
    tokenUsed:{type:Boolean,default:false},
    status:{type:String,enum:['payment-pending','pending','resolved'],default:'payment-pending'},
    resolution:String,
},{timestamps:true})
module.exports=mongoose.model('open-dispute',disputeSchema)